# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d5b2069c3f2eb14bb7e89ee914fa7089feceb898014056defbe91877fd38423067a7fd986d0d858899ce815d2a946fc7eaa30a19101d001f4f0159bfbf2b57

test:
  secret_key_base: 120a7b221f0c1a7904cdbc0f40aff09ab63efbf29d18b47d19e69dc8dbaddbc990fe101a54f56ed571f86c8603c96946454b0f8829ca41d6c2601fa60a4fbb91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
